//! Curated factory default presets and modular synthesizer sound design catalog.

use super::patch::*;

pub fn init_default_patches() -> [ModularPatch; MAX_PATCHES] {
    let mut patches = [ModularPatch::default(); MAX_PATCHES];

    // Patch 4: Saw Bass (Classic Phrygian Roller Bass)
    patches[PATCH_SAW_BASS] = ModularPatch {
        osc_type: OSC_SAW,
        sub_level: 0.55,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 320.0,
        cutoff_env_amt: 1600.0,
        cutoff_key_track: 0.6,
        resonance: 0.35,
        attack: 0.005,
        decay: 0.14,
        sustain: 0.45,
        release: 0.12,
        mod_attack: 0.005,
        mod_decay: 0.10,
        bus_id: BUS_BASS,
        polyphony: 1,
        glide: 0.035,
        filter_drive: 0.4,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.05,
    };

    // Patch 5: Acid Bass (Resonant 303 Screamer)
    patches[PATCH_ACID_BASS] = ModularPatch {
        osc_type: OSC_SAW,
        sub_level: 0.2,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 450.0,
        cutoff_env_amt: 4800.0,
        cutoff_key_track: 1.2,
        resonance: 0.88,
        attack: 0.005,
        decay: 0.18,
        sustain: 0.2,
        release: 0.1,
        mod_attack: 0.005,
        mod_decay: 0.14,
        bus_id: BUS_BASS,
        polyphony: 1,
        glide: 0.05,
        filter_drive: 0.65,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.1,
    };

    // Patch 6: Sub Sine (Deep seismic 808 sub)
    patches[PATCH_SUB_SINE] = ModularPatch {
        osc_type: OSC_SINE,
        sub_level: 0.8,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 180.0,
        cutoff_env_amt: 150.0,
        cutoff_key_track: 0.2,
        resonance: 0.1,
        attack: 0.01,
        decay: 0.25,
        sustain: 0.8,
        release: 0.2,
        mod_attack: 0.01,
        mod_decay: 0.2,
        bus_id: BUS_BASS,
        polyphony: 1,
        glide: 0.06,
        filter_drive: 0.15,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.0,
    };

    // Patch 7: Dark Pad (Atmospheric minor chord pad)
    patches[PATCH_DARK_PAD] = ModularPatch {
        osc_type: OSC_SUPERSAW,
        sub_level: 0.3,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 850.0,
        cutoff_env_amt: 1400.0,
        cutoff_key_track: 0.8,
        resonance: 0.3,
        attack: 0.25,
        decay: 0.6,
        sustain: 0.7,
        release: 1.2,
        mod_attack: 0.3,
        mod_decay: 0.8,
        bus_id: BUS_SPACE,
        polyphony: 8,
        glide: 0.0,
        filter_drive: 0.1,
        noise_level: 0.02,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.12,
    };

    // Patch 8: Lead (Cutting sync lead)
    patches[PATCH_LEAD] = ModularPatch::default_lead();

    // Patch 9: FM Chime / Metallic Perc
    patches[PATCH_FM] = ModularPatch {
        osc_type: OSC_FM,
        sub_level: 0.0,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 3800.0,
        cutoff_env_amt: 4000.0,
        cutoff_key_track: 1.0,
        resonance: 0.3,
        attack: 0.005,
        decay: 0.3,
        sustain: 0.1,
        release: 0.3,
        mod_attack: 0.005,
        mod_decay: 0.25,
        bus_id: BUS_SPACE,
        polyphony: 6,
        glide: 0.0,
        filter_drive: 0.15,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.02,
    };

    // Patch 10: Reese Bass (Dark detuned jungle reese)
    patches[PATCH_REESE] = ModularPatch {
        osc_type: OSC_REESE,
        sub_level: 0.45,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 420.0,
        cutoff_env_amt: 1200.0,
        cutoff_key_track: 0.5,
        resonance: 0.4,
        attack: 0.01,
        decay: 0.3,
        sustain: 0.8,
        release: 0.2,
        mod_attack: 0.01,
        mod_decay: 0.2,
        bus_id: BUS_BASS,
        polyphony: 1,
        glide: 0.04,
        filter_drive: 0.55,
        noise_level: 0.01,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.15,
    };

    // Patch 11: Click (Metronome click downbeat/beat)
    patches[PATCH_CLICK] = ModularPatch {
        osc_type: OSC_CLICK,
        sub_level: 0.0,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 8000.0,
        cutoff_env_amt: 0.0,
        cutoff_key_track: 1.0,
        resonance: 0.1,
        attack: 0.001,
        decay: 0.025,
        sustain: 0.0,
        release: 0.015,
        mod_attack: 0.001,
        mod_decay: 0.01,
        bus_id: BUS_DIRECT,
        polyphony: 2,
        glide: 0.0,
        filter_drive: 0.1,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.0,
    };

    // Patch 12: Supersaw (Trance/Hardcore detuned stack)
    patches[PATCH_SUPERSAW] = ModularPatch {
        osc_type: OSC_SUPERSAW,
        sub_level: 0.35,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 2200.0,
        cutoff_env_amt: 4500.0,
        cutoff_key_track: 1.0,
        resonance: 0.35,
        attack: 0.01,
        decay: 0.2,
        sustain: 0.6,
        release: 0.25,
        mod_attack: 0.01,
        mod_decay: 0.2,
        bus_id: BUS_LEAD,
        polyphony: 4,
        glide: 0.02,
        filter_drive: 0.3,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.08,
    };

    // Patch 13: Blade Runner Brass Lead
    patches[PATCH_BLADE] = ModularPatch {
        osc_type: OSC_BLADE,
        sub_level: 0.2,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 950.0,
        cutoff_env_amt: 3200.0,
        cutoff_key_track: 1.1,
        resonance: 0.5,
        attack: 0.08,
        decay: 0.4,
        sustain: 0.7,
        release: 0.8,
        mod_attack: 0.1,
        mod_decay: 0.5,
        bus_id: BUS_SPACE,
        polyphony: 4,
        glide: 0.08,
        filter_drive: 0.25,
        noise_level: 0.02,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.15,
    };

    // Patch 14: Hoover Synth (Alpha Juno Mentasm)
    patches[PATCH_HOOVER] = ModularPatch {
        osc_type: OSC_HOOVER,
        sub_level: 0.4,
        pulse_width: 0.4,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 1800.0,
        cutoff_env_amt: 3600.0,
        cutoff_key_track: 0.8,
        resonance: 0.55,
        attack: 0.01,
        decay: 0.25,
        sustain: 0.6,
        release: 0.2,
        mod_attack: 0.01,
        mod_decay: 0.2,
        bus_id: BUS_LEAD,
        polyphony: 2,
        glide: 0.06,
        filter_drive: 0.45,
        noise_level: 0.0,
        pitch_snap: 24.0,
        pitch_snap_decay: 0.045,
        analog_drift: 0.12,
    };

    // Patch 15: Karplus-Strong Acoustic Pluck
    patches[PATCH_KARPLUS] = ModularPatch {
        osc_type: OSC_KARPLUS,
        sub_level: 0.0,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 6000.0,
        cutoff_env_amt: 0.0,
        cutoff_key_track: 1.0,
        resonance: 0.1,
        attack: 0.002,
        decay: 0.4,
        sustain: 0.0,
        release: 0.3,
        mod_attack: 0.002,
        mod_decay: 0.3,
        bus_id: BUS_SPACE,
        polyphony: 6,
        glide: 0.0,
        filter_drive: 0.0,
        noise_level: 0.8,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.0,
    };

    // Patch 16: Tonewheel Organ (Gospel / House Organ)
    patches[PATCH_ORGAN] = ModularPatch {
        osc_type: OSC_ORGAN,
        sub_level: 0.5,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 4500.0,
        cutoff_env_amt: 1000.0,
        cutoff_key_track: 1.0,
        resonance: 0.2,
        attack: 0.003,
        decay: 0.05,
        sustain: 0.9,
        release: 0.05,
        mod_attack: 0.003,
        mod_decay: 0.05,
        bus_id: BUS_LEAD,
        polyphony: 6,
        glide: 0.0,
        filter_drive: 0.35,
        noise_level: 0.0,
        pitch_snap: 12.0,
        pitch_snap_decay: 0.008,
        analog_drift: 0.02,
    };

    // Patch 17: Chiptune NES Square (8-bit Arpeggiator Lead)
    patches[PATCH_CHIPTUNE] = ModularPatch {
        osc_type: OSC_CHIPTUNE,
        sub_level: 0.0,
        pulse_width: 0.25,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 8000.0,
        cutoff_env_amt: 0.0,
        cutoff_key_track: 1.0,
        resonance: 0.0,
        attack: 0.001,
        decay: 0.08,
        sustain: 0.7,
        release: 0.04,
        mod_attack: 0.001,
        mod_decay: 0.08,
        bus_id: BUS_DIRECT,
        polyphony: 2,
        glide: 0.0,
        filter_drive: 0.1,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.0,
    };

    // Patch 19: Ambient Glass Drift (Shimmering crystal pad)
    patches[PATCH_AMBIENT_GLASS] = ModularPatch {
        osc_type: OSC_SINE,
        sub_level: 0.2,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 1400.0,
        cutoff_env_amt: 2200.0,
        cutoff_key_track: 1.0,
        resonance: 0.25,
        attack: 0.4,
        decay: 0.8,
        sustain: 0.7,
        release: 1.6,
        mod_attack: 0.5,
        mod_decay: 1.0,
        bus_id: BUS_SPACE,
        polyphony: 8,
        glide: 0.0,
        filter_drive: 0.05,
        noise_level: 0.01,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.18,
    };

    // Patch 27: Ethereal Pad
    patches[PATCH_ETHEREAL_PAD] = ModularPatch {
        osc_type: OSC_SUPERSAW,
        sub_level: 0.3,
        pulse_width: 0.5,
        filter_type: FILTER_BANDPASS,
        cutoff_base: 1100.0,
        cutoff_env_amt: 1800.0,
        cutoff_key_track: 0.8,
        resonance: 0.45,
        attack: 0.35,
        decay: 0.7,
        sustain: 0.65,
        release: 1.4,
        mod_attack: 0.4,
        mod_decay: 0.9,
        bus_id: BUS_SPACE,
        polyphony: 8,
        glide: 0.0,
        filter_drive: 0.1,
        noise_level: 0.02,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.14,
    };

    // Patch 28: Ice Pad (Cold, sharp digital pad)
    patches[PATCH_ICE_PAD] = ModularPatch {
        osc_type: OSC_PULSE,
        sub_level: 0.1,
        pulse_width: 0.2,
        filter_type: FILTER_HIGHPASS,
        cutoff_base: 650.0,
        cutoff_env_amt: 1200.0,
        cutoff_key_track: 0.9,
        resonance: 0.3,
        attack: 0.2,
        decay: 0.5,
        sustain: 0.7,
        release: 1.0,
        mod_attack: 0.25,
        mod_decay: 0.6,
        bus_id: BUS_SPACE,
        polyphony: 8,
        glide: 0.0,
        filter_drive: 0.05,
        noise_level: 0.03,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.08,
    };

    // Patch 29: Warm Strings (Analog polyphonic string ensemble)
    patches[PATCH_WARM_STRINGS] = ModularPatch {
        osc_type: OSC_SAW,
        sub_level: 0.25,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 1250.0,
        cutoff_env_amt: 2100.0,
        cutoff_key_track: 0.9,
        resonance: 0.25,
        attack: 0.15,
        decay: 0.4,
        sustain: 0.75,
        release: 0.8,
        mod_attack: 0.2,
        mod_decay: 0.5,
        bus_id: BUS_SPACE,
        polyphony: 8,
        glide: 0.0,
        filter_drive: 0.2,
        noise_level: 0.01,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.16,
    };

    // Patch 30: Choir Pad (Vocal formant simulation)
    patches[PATCH_CHOIR_PAD] = ModularPatch {
        osc_type: OSC_PULSE,
        sub_level: 0.3,
        pulse_width: 0.35,
        filter_type: FILTER_BANDPASS,
        cutoff_base: 800.0,
        cutoff_env_amt: 950.0,
        cutoff_key_track: 0.6,
        resonance: 0.65,
        attack: 0.3,
        decay: 0.6,
        sustain: 0.7,
        release: 1.2,
        mod_attack: 0.35,
        mod_decay: 0.7,
        bus_id: BUS_SPACE,
        polyphony: 8,
        glide: 0.0,
        filter_drive: 0.15,
        noise_level: 0.02,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.12,
    };

    // Patch 31: Space Drone (Continuous atmospheric evolving drone)
    patches[PATCH_SPACE_DRONE] = ModularPatch {
        osc_type: OSC_SUPERSAW,
        sub_level: 0.6,
        pulse_width: 0.5,
        filter_type: FILTER_NOTCH,
        cutoff_base: 550.0,
        cutoff_env_amt: 800.0,
        cutoff_key_track: 0.3,
        resonance: 0.75,
        attack: 0.8,
        decay: 1.5,
        sustain: 0.9,
        release: 2.5,
        mod_attack: 1.0,
        mod_decay: 2.0,
        bus_id: BUS_SPACE,
        polyphony: 4,
        glide: 0.15,
        filter_drive: 0.3,
        noise_level: 0.05,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.25,
    };

    // Patch 32: Pluck Lead (Bright fast EDM/Trance pluck)
    patches[PATCH_PLUCK_LEAD] = ModularPatch {
        osc_type: OSC_PULSE,
        sub_level: 0.2,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 1200.0,
        cutoff_env_amt: 5200.0,
        cutoff_key_track: 1.2,
        resonance: 0.5,
        attack: 0.002,
        decay: 0.12,
        sustain: 0.0,
        release: 0.1,
        mod_attack: 0.002,
        mod_decay: 0.09,
        bus_id: BUS_LEAD,
        polyphony: 4,
        glide: 0.0,
        filter_drive: 0.25,
        noise_level: 0.0,
        pitch_snap: 12.0,
        pitch_snap_decay: 0.01,
        analog_drift: 0.04,
    };

    // Patch 33: Neuro Bass (Heavy distorted modulated neurofunk bass)
    patches[PATCH_NEURO_BASS] = ModularPatch {
        osc_type: OSC_REESE,
        sub_level: 0.5,
        pulse_width: 0.5,
        filter_type: FILTER_BANDPASS,
        cutoff_base: 380.0,
        cutoff_env_amt: 2200.0,
        cutoff_key_track: 0.8,
        resonance: 0.72,
        attack: 0.008,
        decay: 0.2,
        sustain: 0.7,
        release: 0.18,
        mod_attack: 0.01,
        mod_decay: 0.16,
        bus_id: BUS_BASS,
        polyphony: 1,
        glide: 0.045,
        filter_drive: 0.85,
        noise_level: 0.02,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.15,
    };

    // Patch 34: 808 Sub (Pure sub-bass with punchy pitch envelope)
    patches[PATCH_808_SUB] = ModularPatch {
        osc_type: OSC_SINE,
        sub_level: 0.9,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 120.0,
        cutoff_env_amt: 80.0,
        cutoff_key_track: 0.1,
        resonance: 0.0,
        attack: 0.005,
        decay: 0.45,
        sustain: 0.6,
        release: 0.35,
        mod_attack: 0.005,
        mod_decay: 0.3,
        bus_id: BUS_BASS,
        polyphony: 1,
        glide: 0.05,
        filter_drive: 0.3,
        noise_level: 0.0,
        pitch_snap: 36.0,
        pitch_snap_decay: 0.025,
        analog_drift: 0.0,
    };

    // Patch 35: Slap Bass (Percussive funk slap bass)
    patches[PATCH_SLAP_BASS] = ModularPatch {
        osc_type: OSC_PULSE,
        sub_level: 0.3,
        pulse_width: 0.4,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 650.0,
        cutoff_env_amt: 3800.0,
        cutoff_key_track: 1.0,
        resonance: 0.55,
        attack: 0.003,
        decay: 0.14,
        sustain: 0.3,
        release: 0.08,
        mod_attack: 0.003,
        mod_decay: 0.1,
        bus_id: BUS_BASS,
        polyphony: 1,
        glide: 0.02,
        filter_drive: 0.4,
        noise_level: 0.05,
        pitch_snap: 24.0,
        pitch_snap_decay: 0.015,
        analog_drift: 0.05,
    };

    // Patch 36: Organ Bass (Deep house M1-style organ bass)
    patches[PATCH_ORGAN_BASS] = ModularPatch {
        osc_type: OSC_ORGAN,
        sub_level: 0.4,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 850.0,
        cutoff_env_amt: 1800.0,
        cutoff_key_track: 0.8,
        resonance: 0.3,
        attack: 0.003,
        decay: 0.16,
        sustain: 0.5,
        release: 0.1,
        mod_attack: 0.003,
        mod_decay: 0.12,
        bus_id: BUS_BASS,
        polyphony: 1,
        glide: 0.03,
        filter_drive: 0.3,
        noise_level: 0.0,
        pitch_snap: 12.0,
        pitch_snap_decay: 0.012,
        analog_drift: 0.03,
    };

    // Patch 37: Acid Lead (High resonant squealing 303 lead)
    patches[PATCH_ACID_LEAD] = ModularPatch {
        osc_type: OSC_SAW,
        sub_level: 0.1,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 950.0,
        cutoff_env_amt: 6200.0,
        cutoff_key_track: 1.3,
        resonance: 0.92,
        attack: 0.004,
        decay: 0.15,
        sustain: 0.25,
        release: 0.12,
        mod_attack: 0.004,
        mod_decay: 0.12,
        bus_id: BUS_LEAD,
        polyphony: 2,
        glide: 0.06,
        filter_drive: 0.75,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.12,
    };

    // Patch 38: FM Bell (Bright crystalline FM bell)
    patches[PATCH_FM_BELL] = ModularPatch {
        osc_type: OSC_FM,
        sub_level: 0.0,
        pulse_width: 0.5,
        filter_type: FILTER_BANDPASS,
        cutoff_base: 2400.0,
        cutoff_env_amt: 3500.0,
        cutoff_key_track: 1.0,
        resonance: 0.6,
        attack: 0.002,
        decay: 0.65,
        sustain: 0.0,
        release: 0.5,
        mod_attack: 0.002,
        mod_decay: 0.45,
        bus_id: BUS_SPACE,
        polyphony: 6,
        glide: 0.0,
        filter_drive: 0.1,
        noise_level: 0.0,
        pitch_snap: 0.0,
        pitch_snap_decay: DEFAULT_PITCH_SNAP_DECAY_SEC,
        analog_drift: 0.02,
    };

    // Patch 39: Glass Keys (Delicate ambient electric piano keys)
    patches[PATCH_GLASS_KEYS] = ModularPatch {
        osc_type: OSC_SINE,
        sub_level: 0.25,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 2800.0,
        cutoff_env_amt: 2400.0,
        cutoff_key_track: 1.0,
        resonance: 0.2,
        attack: 0.004,
        decay: 0.35,
        sustain: 0.3,
        release: 0.4,
        mod_attack: 0.004,
        mod_decay: 0.3,
        bus_id: BUS_SPACE,
        polyphony: 6,
        glide: 0.0,
        filter_drive: 0.1,
        noise_level: 0.0,
        pitch_snap: 12.0,
        pitch_snap_decay: 0.006,
        analog_drift: 0.04,
    };

    // Patch 40: Siren (Dub sound system laser siren)
    patches[PATCH_SIREN] = ModularPatch {
        osc_type: OSC_SAW,
        sub_level: 0.3,
        pulse_width: 0.5,
        filter_type: FILTER_BANDPASS,
        cutoff_base: 1800.0,
        cutoff_env_amt: 3200.0,
        cutoff_key_track: 0.0,
        resonance: 0.8,
        attack: 0.01,
        decay: 0.4,
        sustain: 0.6,
        release: 0.4,
        mod_attack: 0.01,
        mod_decay: 0.35,
        bus_id: BUS_SPACE,
        polyphony: 1,
        glide: 0.12,
        filter_drive: 0.5,
        noise_level: 0.0,
        pitch_snap: 48.0,
        pitch_snap_decay: 0.12,
        analog_drift: 0.2,
    };

    // Patch 41: Laser (High sci-fi arcade zap)
    patches[PATCH_LASER] = ModularPatch {
        osc_type: OSC_PULSE,
        sub_level: 0.0,
        pulse_width: 0.5,
        filter_type: FILTER_LOWPASS,
        cutoff_base: 5000.0,
        cutoff_env_amt: 6000.0,
        cutoff_key_track: 0.0,
        resonance: 0.65,
        attack: 0.001,
        decay: 0.08,
        sustain: 0.0,
        release: 0.06,
        mod_attack: 0.001,
        mod_decay: 0.06,
        bus_id: BUS_DIRECT,
        polyphony: 2,
        glide: 0.0,
        filter_drive: 0.4,
        noise_level: 0.0,
        pitch_snap: 48.0,
        pitch_snap_decay: 0.035,
        analog_drift: 0.0,
    };

    patches
}
