name: Deploy Release to GitHub Pages

on:
  push:
    tags:
      - "v*"
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build + Deploy to Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Lint source & tests
        run: nix develop --command clj-kondo --lint src test

      - name: Run unit test suite
        run: nix develop --command pnpm test

      - name: Build production release bundle
        run: nix develop --command pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
